services:
  nginx:
    build:
      context: ./nginx
    image: nginx

    container_name: "nginx_cont"

    ports:
      - "80:80"

    networks:
      - notes-app

    restart: always

    depends_on:
      - django


  django:
    build: 
      context: .

    image: django_app

    container_name: "django_cont" 

    networks:
      - notes-app

    restart: always

    depends_on: 
      - db

    ports:
      - "8000:8000"

    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"

    env_file:
      - ".env"  

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  db:
    image: mysql
    container_name: "db_cont"

    ports:
      - "3306:3306"

    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql

    networks:
      - notes-app

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

     
networks:
  notes-app:
